module Prometheus
  module Client
    module Rust
      module Datastores
        VERSION: String
        # See the writing guide of rbs: https://github.com/ruby/rbs#guides
      end
    end
  end
end
